### ISSUE TITLE
the read me is not popping up in the canva site

### ISSUE THREAD

**Issue by mendelr20** [learn-co-curriculum/phase-3-sql-intro-introduction#1]
### Canvas Link

https://learning.flatironschool.com/courses/4972/pages/sql-practice-musicdb?module_item_id=352482

### Concern

the read me is not popping up in the canva site

**Comment by lizbur10** [comment]
Hi @mendelr20 ! Thank you for bringing this to our attention. The correct lesson should now be available in Canvas: https://learning.flatironschool.com/courses/4972/pages/introduction-to-sql?module_item_id=352482

Thanks for contributing to the Flatiron School curriculum 💙
